rees46/workflow

.github/workflows/reusable-docker-publish-ruby.yaml
Пока только для апи. Когда (если) перейдём на совмещение с дэшбордом буду переделывать тут логику
=> feat: add docker ruby publish

.github/workflows/checks/reusable-js-checks.yaml
подготовка https://github.com/rees46/development/issues/379
=> Feat: check js workflow

.github/workflows/deploy-php.yml
Перевод php-сервисов на Workflow Deploy #399 
Добавил message-service в deploy-php.yml
=> added message-service to services

.github/workflows/reusable-rn-synchronization.yml
- setup assignee
- fix commit name
- fix commit author
=> feat: add CHANGELOG.md to sync

.github/workflows/reusable-rn-synchronization.yml
Относится к: https://github.com/rees46/planning/issues/177
=> feat: fix PR assignee

.github/workflows/deploy-php.yaml
https://github.com/rees46/planning/issues/462
=> feat: add yml and autovaz import processes support

.github/actions/php/changelog-and-publish-php/action.yaml, .github/actions/php/start-php/action.yaml
https://github.com/rees46/planning/issues/532
=> feat: add start and changelog actions

.github/workflows/deploy-php.yaml
https://github.com/rees46/planning/issues/462
=> feat: rename yml service

.github/workflows/deploy-php.yaml
https://github.com/rees46/planning/issues/563
=> feat: add message status service support

.github/workflows/deploy-php.yaml
https://github.com/rees46/planning/issues/563
=> feat: add delay service support

.github/workflows/reusable-php-checks.yaml
=> chore: change running tests configuration

.github/workflows/deploy-php.yaml
https://github.com/rees46/planning/issues/701
=> feat: message status callback support

.github/workflows/reusable-php-checks.yaml
=> fix: elastic container name

.github/workflows/reusable-php-checks.yaml
=> chore: rename elastic service in job

.github/workflows/reusable-php-checks.yaml
=> feat: make elastic container naming dynamic

.github/workflows/reusable-php-checks.yaml
=> feat: make volume instead of copy

.github/workflows/reusable-php-checks.yaml
=> feat: add github workspace to mount elastic path

.github/workflows/reusable-php-checks.yaml
=> chore: copy files instead of mounting

.github/workflows/reusable-php-checks.yaml
=> chore: rename elastic service

.github/workflows/reusable-php-checks.yaml
=> chore: remove elastic wait job

.github/workflows/reusable-php-checks.yaml
=> chore: change container id getting method

.github/workflows/reusable-php-checks.yaml
=> chore: echo docker ps

.github/workflows/reusable-php-checks.yaml
=> chore: create hunspell directory inside container

.github/workflows/reusable-php-checks.yaml
=> feat: add core tests

.github/workflows/reusable-php-checks.yaml
=> fix: core test configuration

.github/workflows/deploy-ruby.yaml
https://github.com/rees46/planning/issues/637
=> chore: added branch parameter to jenkins deploy ruby

.github/workflows/reusable-docker-publish-infrastructure.yaml
https://github.com/rees46/planning/issues/1888
=> chore(private key): update secret to apth through

.github/workflows/deploy-node-trigger.yaml
https://github.com/rees46/development/issues/1934
=> feat(action): create deploy node trigger

.github/workflows/reusable-ios-synchronization.yaml
- https://github.com/rees46/development/issues/2075
=> feat: Change assigning from last PR author to manager

.github/workflows/resuable-issue-management.yaml
относится к https://github.com/rees46/development/issues/2136
=> feat(issue): init

.github/workflows/reusable-docker-publish.yaml
https://github.com/rees46/development/issues/2283
=> fix(reusable-docker-publish): correct changed packages array

.github/workflows/reusable-docker-publish.yaml
https://github.com/rees46/development/issues/2283
[упало](https://github.com/rees46/web/actions/runs/12769066308/job/35594634993#step:5:1), забыл пробел в качестве сепаратора в конце
=> fix(reusable-docker-publish): fix packages list add space separator

.github/workflows/reusable-docker-publish.yaml
https://github.com/rees46/development/issues/2283
[comment](https://github.com/rees46/development/issues/2283#issuecomment-2591902397)
=> feat(reusable-docker-publish): add tag for master branch

.github/workflows/reusable-js-checks.yaml
- у этого экшена переодически повторяется ошибка
- ![image](https://github.com/user-attachments/assets/84071919-8d2a-48d4-96a3-3b922b472585)
- ![image](https://github.com/user-attachments/assets/dacfd601-2c4c-42ad-9e77-5654addedcf4)
- не можем свитчнутсья на ветку, хотя она триггерит экшен и гарантирвоанно должна существовать
=> feat(github): fetch step

.github/workflows/reusable-ios-publish.yaml
for https://github.com/rees46/development/issues/2587#issuecomment-2685130542
=> feat(github): retry ios publish

.github/workflows/reusable-js-checks.yaml
- фетчим ветки по-другому
- т.к. через раз скрипт проходит, скорее всего чтото с задержками
=> feat(workflows): fetch all branches

.github/actions/php/changelog-and-publish-php/action.yaml, .github/workflows/deploy-node-trigger.yaml, .github/workflows/deploy-node.yaml, .github/workflows/deploy-php.yaml, .github/workflows/deploy-ruby.yaml, .github/workflows/reusable-android-google-play-publish.yaml, .github/workflows/reusable-infrastructure-checks-elasticsearch.yaml, .github/workflows/reusable-infrastructure-checks-k8s.yaml, .github/workflows/reusable-ios-synchronization.yaml, .github/workflows/reusable-php-checks.yaml, .github/workflows/reusable-ruby-publish-migrated-db.yaml, .yarnrc.yml, global/github-client/package.json, global/github-client/src/index.ts, package.json, scripts/issue-status-updater/package.json, scripts/issue-status-updater/src/issue-status-updater.ts, scripts/issues-getter/package.json, scripts/project-field-getter/package.json, scripts/project-field-getter/src/project-field-getter.ts, scripts/project-getter/package.json, scripts/project-getter/src/get-project.ts, scripts/project-issue-getter/package.json, scripts/project-issue-getter/src/project-issue-getter.ts, tsconfig.json
=> style(common): format

.github/actions/js/changelog-and-publish-js/action.yaml
меняю конфиг ярна, чтобы он использовал нпм-региср
=> feat(actions): force to use npm registry

.github/actions/js/changelog-and-publish-js/action.yaml, .github/actions/js/delete-release-js/action.yaml, .github/actions/js/release-js/action.yaml, .github/actions/js/version-js/action.yaml
- выключаю `parallel jobs` для ненагруженных экшенов
- сыпятся ошибки. один экшен не успевает закончиться, начинается другой
=> fix(actions): rm parallel jobs

.github/actions/js/changelog-and-publish-js/action.yaml, .github/actions/js/delete-release-js/action.yaml, .github/actions/js/release-js/action.yaml
- экшн отвалился - https://github.com/rees46/dashboard/actions/runs/13583793271/job/37987194696#step:5:11
- если учесть то, что ничего, кроме синтаксиса ключа `--jobs` я не менял, то ошибка гарантированно в нем
=> fix(actions): command syntax

.github/workflows/reusable-android-synchronization.yaml, .github/workflows/reusable-ios-synchronization.yaml
move `target repository` to inputs
=> feat(github): target repo inputs

.github/workflows/reusable-android-google-play-publish.yaml, .github/workflows/reusable-android-synchronization.yaml, .github/workflows/reusable-ios-synchronization.yaml
for https://github.com/rees46/development/issues/2533
- последние 2 запуска успешные - https://github.com/rees46/demo-android/actions/workflows/publish.yaml
- взял за основу apk-build и перебил по аналогии
=> fix(github): android publish

.github/workflows/reusable-android-synchronization.yaml
for https://github.com/rees46/development/issues/2533
- пропетрис оставляем персоновские
- заменяем один пакет на персоновский
=> feat(github): android sync

.github/workflows/reusable-android-synchronization.yaml
for https://github.com/rees46/development/issues/2654
* feat(github): files to exclude
* feat(github): persona sdk package regex
refactor(github): useless
* feat(github): files to exclude
* feat(github): persona sdk package regex
refactor(github): useless
* feat(github): files to exclude
* feat(github): persona sdk package regex
=> refactor(github): useless

.github/workflows/reusable-ios-synchronization.yaml
- добавил читстку директорий перед `rsync`
=> fix(github): clean target repo before rsync

.github/workflows/reusable-ios-testflight-publish.yaml, .github/workflows/reusable-multiplatform-bump.yaml
for https://github.com/rees46/development/issues/2709
- вытащил бамп и коммит в индивидуальный вокфлоу
=> refactor(github): separate multiplatform bump

.github/workflows/reusable-ios-synchronization.yaml, .github/workflows/reusable-multiplatform-bump.yaml
for https://github.com/rees46/development/issues/2713
- расширяю версионирование - гдето используется подспек, гдето версион.пропертис
- меняю чистку, предыдущая не работала
- использую скрипты из воркфлоу
- добавляю ренейм директорий
=> feat(github): sync

.github/workflows/reusable-android-version.yaml
for https://github.com/rees46/development/issues/2723
- удаляю лишниее. для версионирования + коммита столько не надо
- в экшен провел дебаг, без коммита. в шагах `debug git` видно, что версия поднялась - https://github.com/rees46/android-sdk/actions/runs/14142780982/job/39626396505
=> refactor(github): reusable android version

.github/actions/utils/fs/rename-files/action.yml, .github/workflows/reusable-ios-synchronization.yaml
for https://github.com/rees46/development/issues/2714
proof https://github.com/PersonaClick/ios-sdk/pull/94
- переиспользую actions из самых актуальных workflows
=> refactor(github): reusable ios synchronization

.github/workflows/reusable-android-publish.yaml, .github/workflows/reusable-android-version.yaml
for https://github.com/rees46/development/issues/2746
- checkout переключался на неактуальное состояние ветки - после бамба была устаревшая версия
- поправил пропсы, передаваемые в checkout
=> fix(github): android version

.github/actions/android/prepare/action.yaml, .github/workflows/reusable-android-publish.yaml
for https://github.com/atls/kmp/issues/5
- добавляю запись gpg-ключа в gradle.properties
- как понял, в новых версиях нельзя работать с ключом как с файлом, нужна строка
=> feat(github): sonatype publish

.github/actions/git/add/action.yml, .github/workflows/reusable-ios-synchronization.yaml
for https://github.com/rees46/development/issues/2714
- была ошибка в ветке воркфлоу. ссылалася на ветку для разработки
- вынес работу с гитом в свой экшен
=> fix(github): ios sync

scripts/repo-replacement/src/interfaces/config.interface.ts, scripts/repo-replacement/src/replacement-processors/directory.replacements-processor.ts
for https://github.com/rees46/development/issues/2654
- добавляю игнор в replacement-скрипт
=> feat(scripts): ignore replacements

.github/actions/github/pull-request/get-last-author/action.yml, .github/actions/release/prepare-pr/action.yml, .github/actions/sync/prepare-pr/action.yml, .github/workflows/reusable-repo-sync.yml
for https://github.com/rees46/development/issues/2654
latest: https://github.com/rees46/android-sdk/actions/runs/14672242112/job/41181358436
- была ошибка с тем, что пытались назначить assignee бота
=> fix(github): action

.github/workflows/reusable-android-google-play-publish.yaml
for https://github.com/rees46/development/issues/2781
proof: https://play.google.com/store/apps/details?id=personaClick.demo_shop&hl=en-US&ah=kjFrFzzLARW_NUPotwXZnkFwlhc&pli=1
- убираю один проп, с ним была ошибка
- добавляю вывод в лог юрл для скачивания
после мерджа:
1. вмерджить персону
2. добавить в rees/demo-android, replacements commit-hash персоны в publish-workflow
=> refactor(github): rm prop from action; with it didnt work

.github/actions/release/prepare-pr/action.yml, scripts/clean-directory/src/entrypoint.ts, scripts/repo-replacement/src/entrypoint.ts, scripts/repo-replacement/src/interfaces/directory-replacements-processor.interface.ts, scripts/repo-replacement/src/interfaces/file-content-replacement-processor.interface.ts
for https://github.com/rees46/development/issues/2715
- добавляю Info.plist в коммит при бампе
- отформатировал scripts
=> feat(github): release workflow

.github/actions/release/prepare-pr/action.yml, .github/workflows/reusable-multiplatform-version-bump.yaml
for https://github.com/rees46/development/issues/2715
proof: https://github.com/rees46/demo-ios/actions/runs/14849003858
- правил пропс для экшена
=> fix(github): version workflow

.github/workflows/reusable-multiplatform-version-bump.yaml, .pnp.cjs, scripts/check-vars/package.json, scripts/clean-directory/package.json, scripts/issue-status-updater/package.json, scripts/issues-getter/package.json, scripts/project-field-getter/package.json, scripts/project-getter/package.json, scripts/project-issue-getter/package.json, scripts/repo-replacement/package.json, yarn.lock
for https://github.com/rees46/development/issues/2654#issuecomment-2840111953
- pass GH_TOKEN to action
- почемуто первый раз его просит https://github.com/rees46/android-sdk/actions/runs/14868295661/job/41750456242#step:6:54
- добавил @types/node, в js-пакеты, отвалился синк после бампа бандла
=> feat(github): pass token to action

.github/actions/release/prepare-pr/action.yml
for https://github.com/rees46/development/issues/2921
- убираю filepattern
- этот экшен вызывается только из release-workflow. в нем лишних изменений не будет
=> refactor(github): rm useless

.github/actions/sync/read-replacements/action.yml
closes https://github.com/rees46/development/issues/2926
proof https://github.com/rees46/development/issues/2926#issuecomment-2877967530
- перенес replacements из репозиториев в infrastructure
- поправил prepare-sync-acition. делаем чекаут на инфру, работаем с ней
=> refactor(github): replacements

.github/workflows/reusable-js-publish.yaml, .github/workflows/reusable-js-version.yaml
for https://github.com/rees46/development/issues/2976
- добавляю exclue-prop для версионирвоания и паблиша
=> feat(github): provide exclude prop

.github/workflows/repo-sync.yaml
for https://github.com/rees46/development/issues/2976
proof https://github.com/rees46/workflow/actions/runs/15185903015
- добавил айдишник для step
=> fix(github): step id

.github/actions/github/utils/get-new-branch-name/action.yml, .github/actions/sync/prepare-pr/action.yml, .github/workflows/auto-merge-sync-pr.yml.bak
for https://github.com/rees46/development/issues/2976
- прокидываю baseBranchName prop до экшена
- при синке буду созадватть sync-ветки
=> feat(github): pass baseBranchName prop to create new branch action

.github/actions/github/pull-request/create/action.yml, .github/actions/release/prepare-pr/action.yml, .github/workflows/reusable-js-version.yaml
for https://github.com/rees46/development/issues/2939
proof - https://github.com/rees46/workflow-tests/pull/156
- авто-мердж
- фикс бага - https://github.com/rees46/web/actions/runs/15396854946
=> refactor(github): workflow

.github/actions/github/pull-request/create/action.yml
for https://github.com/rees46/development/issues/2939
- подпись коммитов
=> feat(github): sign commits

.github/actions/github/pull-request/create/action.yml, .github/workflows/reusable-multiplatform-version-bump.yaml, .github/workflows/reusable-release-commit-finder.yaml
for https://github.com/rees46/development/issues/2921
proof https://github.com/rees46/loyalty-program/actions/runs/15928262427/job/44930766299
proof https://github.com/rees46/loyalty-program/pull/69
=> fix(github): version multiplatform

.github/actions/js/start-js/action.yaml
for https://github.com/rees46/development/issues/3134
=> feat(github): owner to th-token-action

.github/workflows/repo-sync.yaml
https://github.com/rees46/development/issues/3075
=> fix(personaclick): reviewer

.github/workflows/reusable-ios-checks.yaml
**Таска:**
- https://t.me/c/2243138785/316/56815
=> Remove extra env from tests
